### ISSUE TITLE
how should cleanHostValue behave?

### ISSUE THREAD

**Issue by remusao** [oncletom/tld.js#101]
Hi,

I played for a while with writing a more efficient version of `cleanHostValue`, and stumbled upon a lot of corner cases that are either not handled properly by `url.parse` from nodejs, or not handled properly by `cleanHostValue` (or both at the same time). So I'd like to open this issue to discuss what we actually expect from this function:

1. Do we expect it to try very hard to extract a `hostname` from the string given as argument? Even if the standard would not consider it a valid URL? e.g.: `mailto:foo@bar` will return `bar` as a hostname, although there is none => Chrome and Firefox return `null`. To understand why, what should be hostname of `mailto:foo@bar,foo@baz`? We will return `bar`. Other example: `protocol://foo.org` will have a `null` hostname on Firefox but we will return `foo.org`, on the other hand `cleanHostValue` will return `protocol` if we give it `protocol:foo.org` but `url.parse` will still give `foo.org`.

2. Do we expect it to be very strict and follow the spec? Which is not currently the case for two reasons:
    1. We transform the URL before calling `url.parse` on it (we add `//` if we don't detect a scheme, although `url.parse` would happily give `foo.org` as a hostname for `protocol:foo.org` but `cleanHostValue` will return `protocol` instead)
    2. `url.parse` does not comply to the specification (or is buggy?), in several cases: `mailto:foo@bar` is one, `protocol:host` is another (`url.parse` will return `host`, but Firefox and Chrome will return `null`). There are more.

Somehow I feel like `1.` would make more sense, since we already don't respect the spec, maybe we could make the behavior a bit more sane/predictable, and more efficient than the current implementation. Also, writing a spec-compliant parser is a very hard job (nodejs did not get it right, yet).

But then we will introduce a breaking change in the API, if people rely on the current behavior (https://xkcd.com/1172/).

What do you think?

**Comment by remusao** [comment]
I found quite a few other differences between `url.parse` and Firefox's `new URL()` parser:

|input|nodejs url.parse|firefox|
|-------|----------------------|--------|
|`mid:m@example.ord/m2@example.ord/c2@example.org`|`example.ord`|`null`|
|`mid:m@example.ord/c@example.org`|`example.ord`|`null`|
|`https:host2`|`null`|`host2`|
|`httpa://foo:80/`|`foo`|`null`|
|`http:this`|`null`|`this`|
|`http:/path`|`null`|`path`|
|`http://x]/`|`x`|`null`|
|`http://www.yaho%6f.com`|`www.yaho`|`www.yahoo.com`|
|`http://www.w%33.org`|`www.w`|`www.w3.org`|
|`http://www.lookout.net::==80::==443::`|`www.lookout.net`|`null`|
|`http://www.lookout.net&#xFF1A;80`|`www.lookout.net`|`www.lookout.net&`|
|`http://www.example.com:as%20df/`|`www.example.com`|`null`|
|`http://www%20.lookout.net/`|`www`|`www%20.lookout.net`|
|`http://w3c.org:80path1/path2`|`w3c.org`|`null`|
|`http://user:pass@[::1]:80?query#frag`|`::1`|`[::1]`|
|`http://user%3Ainfo%40example.com`|`user`|`user%3ainfo%40example.com`|
|`http://foo%CC%80.bar.com/`|`foo`|`xn--fo-3ja.bar.com`|
|`http://�.net/`|`�.net`|`xn--zn7c.net`|
|`http://\google.com/foo`|`null`|`google.com`|
|`http://[xyz]/`|`xyz`|`null`|
|`http://\./`|`null`|`.`|
|`http://&#xff10;&#xff38;[...]`|`null`|`&`|
|`http://.:.`|`.`|`null`|
|`file://meetings.example.com/cal#m1`|`meetings.example.com`|`null`|
|`data:image/png;base64,iVBORw0KGgoAAAA[...]`|`image`|`null`|

**Comment by oncletom** [comment]
I initially assumed very naively Node URL parser was doing a correct job but you just proved it's not the case ;-) Firefox URL parser looks very good!

I wonder if that should not be addressed directly at the Node.js level, and if Firefox URL parser is available as an npm module, we could totally use it.

**Comment by remusao** [comment]
I assume their parser has a very efficient implementation in C++ somewhere. Moreover, I think they also do parsing delegation depending on the scheme. Which means they detect what scheme/protocol the url is, then call a different parser. You can also register your own protocols and provide a custom parser, but that's another story. Let's see if there is another option for parsing, but I'm not sure. If we agree we want to have the same behavior than Firefox (that will be a pretty major breaking change), we can try to find one or implement one ourselves.

**Comment by oncletom** [comment]
It seems to agitate a few conversation in the Node.js issues 😉 

Cf. https://github.com/nodejs/node/issues/9550#issuecomment-260007747

I guess https://www.npmjs.com/package/whatwg-url should behave very similarly to Firefox URL parser.

**Comment by remusao** [comment]
Indeed, we could try and see how it behaves with our current test-suite + the corner cases. My concern is that it might do much much more than what we need (just extracting a hostname, which can probably be done much faster than parsing the full URL). They seem to have an extensive test-suite, in the eventuality that their implementation is what we need, we could still implement a custom hostname extractor, using their test-suite as validation to make sure we don't screw this up.

**Comment by remusao** [comment]
I just gave a quick try to `whatwg-url`, there are some interesting cases:
```
new URL('http://c|/').hostname === 'c|';
new URL('http://276.1.2').hostname === null;
new URL('http://276.1.2').hostname === null;
```

Overall they seem to be much more strict than Firefox. And it's probably better than nodejs `url` module. Although according to some benchmarks I performed, it is `10x` slower, which makes sense given the number of checks they perform.

**Comment by oncletom** [comment]
Interestingly, I realised `node@>7.something` added a WHATWG URL parser as `require('url').URL`.

```
> new URL('http://x]/')
TypeError [ERR_INVALID_URL]: Invalid URL: http://x]/
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:120:20)

> new URL('http://www.yaho%6f.com')
URL {
  href: 'http://www.yahoo.com/',
  origin: 'http://www.yahoo.com',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'www.yahoo.com',
  hostname: 'www.yahoo.com',
  port: '',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: '' }
```

More recent versions of Node could benefit of better results if we used `require('url').URL` but it could lead to surprising results if the library is used on older Node installs.

**Comment by remusao** [comment]
@oncletom Do you think this issue is still relevant since users can now specify a custom `extractHostname` method as part of the API? I'm not sure we should try to solve this issue. Avoiding breaking change seems to be safer, and we could add some explanation in the README.md to customize hostname parsing?

**Comment by oncletom** [comment]
@remusao agreed — as long as the URL parser can be swapped, I'm all good with this approach.

**Comment by remusao** [comment]
Closing this one as there is now a way to plug your own URL parsing implementation.
