### ISSUE TITLE
Handle ip addresses

### ISSUE THREAD

**Issue by remusao** [oncletom/tld.js#104]
Hi,

Currently we don't detect if a url contains a hostname or an ip address. We should probably add some check so that we return a consistent result.

Current behavior:
```js
> tldjs.parse('https://123.23.32.31')
{ valid: true,
  hostname: '123.23.32.31',
  suffix: '31',
  domain: '32.31',
  subdomain: '123.23' }
```

Should probably be something like:
```js
> tldjs.parse('https://123.23.32.31')
{ valid: true,
  hostname: '123.23.32.31',
  suffix: null,
  domain: null, // Or `hostname`?
  subdomain: null }
```

**Comment by oncletom** [comment]
Oh, good thinking. I never tried with an IPv6 too but I suppose its syntax would fail on an `isValid` call.

**Comment by remusao** [comment]
What do you think about including some dependency to do this validation? I saw two libraries looking pretty robust:

* https://www.npmjs.com/package/validator (does much more than ip-validation, so that might be overkill)
* https://www.npmjs.com/package/is-ip (only based on regexps, which looks pretty fast and robust)

**Comment by oncletom** [comment]
Well, `validator` has no dependency, has `isDataURI` and`isEmail` (cf. #101).
But the rest is not relevant so it is less nice, bundle size wise.

PS: funnily, it has a `isFQDN` method 😉

**Comment by remusao** [comment]
So did I understand correctly that we should use `is-ip` instead? Or do you think it's worth it to integrate also checks for `isEmail` and `isDataURI`?

PS: funnily, `isFQDN` is `10x` slower than `isValid` :P

**Comment by oncletom** [comment]
Yeah let's go ahead with `is-ip`. We can swap it with something else if needed in the future.

PS: 😂

**Comment by remusao** [comment]
@oncletom I started adding the support for ip addressed in `tld.js`. Will do a PR when it's ready. I might also try to switch to `whatwg-url` for parsing if it works out fine.

**Comment by remusao** [comment]
IP addresses are now detected since #108.
