### ISSUE TITLE
big subdomain names returns null

### ISSUE THREAD

**Issue by qanuj** [oncletom/tld.js#110]
`var tld = require('tldjs');
var host='https://some-very-big-name-at-this-subdomain.azurewebsites.net/';
console.log("Subdomain -->",tld.getSubdomain(host))`

_should_ print **some-very-big-name-at-this-subdomain** prints **blank**;

`console.log("Domain -->",tld.getDomain(host))` 

_should_ print **azurewebsites.net** prints **some-very-big-name-at-this-subdomain.azurewebsites.net**

**Comment by remusao** [comment]
Hi @qanuj,

We currently enforce some limitation on the maximum size of a hostname and its labels. According to http://www.freesoft.org/CIE/RFC/1035/ ([section 2.3.4](http://www.freesoft.org/CIE/RFC/1035/9.htm)), a label must not be longer than `63` octets. Which seems to be the case for your example.

Did you encounter such a case in the wild? If so, maybe we should relax a bit this constraint, or make it optional? @oncletom

**Comment by oncletom** [comment]
@qanuj could you share one of the Azure URLs once one of these environments has been shut down? Would be useful to check it against what @remusao just explained, re the hostname length.

**Comment by remusao** [comment]
@qanuj Any update on your side?

**Comment by oncletom** [comment]
@qanuj I'm going to close the issue — we can reopen it if you or someone else provide the URL. I could not find any satisfying `*.azurewebsites.net` URL on the web :-(
