### ISSUE TITLE
Got wrong TLD for URL se.com

### ISSUE THREAD

**Issue by henryhuang2013** [oncletom/tld.js#140]
HI,
I tried URL : "http://www.se.com" and got TLD: se.com.  do you know what happen? 

Thanks.

**Comment by remusao** [comment]
Hey @henryhuang2013,

Looks like the snapshot of the rules used by default is out-dated. Can you try the following after installing `tldjs`:

```sh
cd node_modules/tldjs/ && npm run update && cd ../..
```

Or, when you install you can specify the following flag:

```sh
npm install --save tldjs --tldjs-update-rules
```

Let me know if this solves the issue,
Best,

**Comment by henryhuang2013** [comment]
Yes, problem solved. thanks
