### ISSUE TITLE
The .sport TLD is not existing according to tdlExists func

### ISSUE THREAD

**Issue by fioreggianni** [oncletom/tld.js#142]
Domain names which make use of the `.sport` TLD are not marked as valid by the `tldExists` function. 

http://nic.sport/

### How to reproduce  

Via node console:
```
> let tld = require("tldjs")
> tld.tldExists("abc.sport")
false
```

**Comment by remusao** [comment]
Hi @fioreggianni,

Looks like the version of the lists shipped with `tld.js` is not updated automatically. You can force it with:
```
npm install --save tldjs --tldjs-update-rules
```

After running this command it seems like the issue is resolved.

**Comment by fioreggianni** [comment]
Thank you very much, adding that to our `postinstall` hooks in CI/CD
