### ISSUE TITLE
isValid("www.") returns true?

### ISSUE THREAD

**Issue by ervinbrucal** [oncletom/tld.js#58]
Please see attach plunkr snippet

http://plnkr.co/edit/Tk5CEW0xhfmYUlFfZ6do?p=preview

**Comment by oncletom** [comment]
Thanks. Well I guess this function has to be made more solid, to respect the RFC instead of trying to do some cheap detection.

**Comment by myndzi** [comment]
Isn't `www.` technically a valid domain? Like, the canonical domain syntax actually has a `.` at the end, so `www.` would be the TLD `www`, which presumably doesn't exist but that doesn't mean it's an invalid representation...

(Though, looking at the source, the method could probably be robustified, if you're using this library to do validation you're probably using the wrong tool for the job)

**Comment by felixhageloh** [comment]
possibly related: 

the string `you)..` is also considered valid

**Comment by oncletom** [comment]
Since #96 landed and _dots_ are valid trailing characters, I guess we can close this issue :-)
