### ISSUE TITLE
add support for subdomains on localhost

### ISSUE THREAD

**Issue by morganrallen** [oncletom/tld.js#66]
It would be great if subdomains on localhost could be supported. Is there a particular reason it isn't included or simple oversight as it's probably not very commonly needed?

example
------

```
tld.getSubdomain("vhost.localhost"); // should return vhost
```

**Comment by oncletom** [comment]
Nah it is supposed to work. Will investigate this. Thanks!

**Comment by oncletom** [comment]
Okay gotcha. This is related to #25: `getDomain` and `getSubdomain` indeed look for valid TLD (publicly known and listed in the Public Suffix list). And `localhost` is considered as a TLD, not a domain.

Ideally, we'd like a way to enable specific hosts to work on.
