### ISSUE TITLE
Remove .an domain 

### ISSUE THREAD

**Issue by felixhageloh** [oncletom/tld.js#71]
previous issue is here #69

It seems the pull request didn't fix it.

**Comment by oncletom** [comment]
It seems to be listed on https://publicsuffix.org/list/public_suffix_list.dat

Any reason it should not be present?

**Comment by felixhageloh** [comment]
I see! I'm basing this on this https://en.wikipedia.org/wiki/.an
It mentions that that it was discontinued on 31 July 2015,

**Comment by Kureev** [comment]
Well, http://www.una.an/an_domreg/default.asp (source for .an domains) gives me 404.

**Comment by Kureev** [comment]
I've made a PR to the source document you're using (https://github.com/publicsuffix/list/pull/50), hope you can update this library as soon as it'll be merged in :wink: 

Thanks in advance!

**Comment by oncletom** [comment]
Good move thank you 👍 

I have subscribed to the reported issue and we can safely patch bump once the publicsuffixlist patch gets accepted.

**Comment by Kureev** [comment]
@oncletom Done, PR has been merged! Now it's your turn ;)
