### ISSUE TITLE
README shows google.google as an invalid TLD

### ISSUE THREAD

**Issue by danhstevens** [oncletom/tld.js#74]
`.google` is an actual TLD (sigh) so the README should be updated to reflect this.

https://github.com/oncletom/tld.js/blob/master/README.md#tldexists

Outdated example:
```js
tld.tldExists('google.google'); // returns `false` (not an explicit registered TLD)
```

**Comment by caffeinewriter** [comment]
I actually came here to say this. Unless this checks domain registration information, (which, surprisingly, google.google is not registered) this is a very confusing example. If it _does_ check domain registration, it should include something alongside it like `registry.google`, which does in fact exist.

**Comment by oncletom** [comment]
@caffeinewriter the list of valid tld is based on https://publicsuffix.org/ so `google` is a known tld of ours. @danhstevens is right to say by the time this module was created, the `google` tld did not exist and it should be removed as of now.
