### ISSUE TITLE
tldExists(ipv4_1-lagg0-c026.1.lax004.ix.nflxvideo.net) returns False

### ISSUE THREAD

**Issue by guerrerocarlos** [oncletom/tld.js#75]
Seems that if there is an underscore "_" in the domain, it returns False instead of True when checking the existence of the domain TLD

**Comment by ZLightning** [comment]
This is a duplicate of #73

**Comment by oncletom** [comment]
Yeah exactly. I will close it and encourage you to subscribe to #73 to follow the progress around that issue.
