### ISSUE TITLE
Warning for npm 1.4.28

### ISSUE THREAD

**Issue by DavidBruant** [oncletom/tld.js#77]
I get this:
```
npm WARN engine tldjs@1.6.2: wanted: {"node":">= 0.10","npm":">= 2.13.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
```

Not sure this warning is useful; the npm version doesn't seem that important for this package?

**Comment by oncletom** [comment]
@DavidBruant `npm@2` is needed to perform some `version` hooks but it does not require the end user to have it installed, you are correct.
