### ISSUE TITLE
Allow to customize rules.json

### ISSUE THREAD

**Issue by guillaumevincent** [oncletom/tld.js#85]
It will be great if we can customize `rules.json` used by tldjs. 

In order to reduce my bundle size, I would like to use a lighter version of rules.json.

**Comment by oncletom** [comment]
Interesting idea: what would be your criteria to select or exclude stuff from the rules?

**Comment by guillaumevincent** [comment]
I suggest all tld of the [top one million websites from alexa ](http://s3.amazonaws.com/alexa-static/top-1m.csv.zip)

[Does Alexa have a list of its top-ranked websites?](https://support.alexa.com/hc/en-us/articles/200449834-Does-Alexa-have-a-list-of-its-top-ranked-websites-)

**Comment by oncletom** [comment]
I agree with customising but if there is nothing specific which drives you in term of what to be removed, it is hard to go at it with a blind guess. How much does it weigh in the browser gzipped? How much would you like to download instead?

If the point is just dealing with common top gtld, you are better off having fun with RegExp instead, maybe.

**Comment by guillaumevincent** [comment]
A quick test on all tld of the top one million websites from alexa return a 11ko for rules.json instead of 86ko :
[rules.json.txt](https://github.com/oncletom/tld.js/files/536784/rules.json.txt)

I use tld.js in lesspass web app, and it represent ~20% of my bundle size.
When I wrote my app, I imagined something like this : 

```
import rules from './rules.json'
import tld from 'tldjs';
tld.loads(rules).getSubdomain('google.com');
```

**Comment by guillaumevincent** [comment]
I follow your advise with a simple regex : 

```
function getDomainName(urlStr) {
    var matches = urlStr.match(/^https?\:\/\/([^\/?#]+)(?:[\/?#]|$)/i);
    return matches && matches[1];
}
```

Thank you
