### ISSUE TITLE
Tldjs Browser on Bower

### ISSUE THREAD

**Issue by Adrion** [oncletom/tld.js#89]
Hi,
I saw #37 and I'm asking why bower dependency isn't the browserified version ?

**Comment by oncletom** [comment]
Hi @adrion, I don't use bower – do you mean that the dependencies listed in bower.json are different than the ones in the package.json?

**Comment by Adrion** [comment]
I use bower to seperate client dependencies and npm for non-client.
The idea is to have a client-ready lib inside bower dependency. like a dist/ folder with a pre-browserified version :)

**Comment by oncletom** [comment]
Thank you for the details.

I'm not sure it is a good way to version "dynamic" content in git. I would rather push for `dist` artefacts to be built at CI and published in the npm package (which is the way #91 headed over for the rules bundling).

Why not using npm to manage tldjs and to bundle it the way you need for the browser?

**Comment by Adrion** [comment]
It was more for consistency of 3rd party libs and build workflow, I can live with it don't worry ^^

But yes an artefact on the package (not repos) can be a good solution :)
