### ISSUE TITLE
Weird behaviour on Github.io getDomain

### ISSUE THREAD

**Issue by ahmadassaf** [oncletom/tld.js#93]
Hello,

I noticed weird behaviour handling urls from the domain `github.io` using the `getDomain` method.

```javascript
const tld  = require('tldjs');
console.log("tld", tld.getDomain("google.io")); --> google
console.log("tld", tld.getDomain("github.io")); --> null
```
 and i get back `null` on `github.io`

You can check it live in [here](https://runkit.com/ahmadassaf/5908a5b7d089870012695d31)
  
**UPDATE** 

The behaviour extends as well to other functions like `getPublicSuffix`:

```javascript
console.log(tld.getPublicSuffix("google.io")); --> io
console.log(tld.getPublicSuffix("github.io")); --> github.io
```

 Looking forward for your input.

**Comment by oncletom** [comment]
Hello @ahmadassaf,

that's odd indeed. Let me investigate this issue a bit and see how it goes.
In the meantime, feel free to share your own findings.

And thanks a lot for reporting the issue of course 🙂

**Comment by oncletom** [comment]
Okay gotcha. There is a rule in https://publicsuffix.org/list/public_suffix_list.dat with `github.io` and it demonstrates the negative side effect described in #25.

The publicSuffix method returns the expected result: github.io cannot be a domain on its own so cookies can only be created in subdomains under that same domain.

But what `getDomain` should really do, is to care differently about the rules and only acknowledge the known list of gTLDs (like `.io`, `nhs.uk` `whatever.co.uk` etc.).

I guess we can continue the conversation over there 🙂

**Comment by ahmadassaf** [comment]
thanks @oncletom for the pointer .. moving over there :)
