### ISSUE TITLE
TLD addition request

### ISSUE THREAD

**Issue by golyalpha** [oncletom/tld.js#94]
I have been pointed here by the Brave Browser staff.

Could you please add `keybase.pub` to the list of TLDs?

[Link to the post](https://community.brave.com/t/separate-payments-by-subdomain-in-keybase-pub/4756)

**Comment by oncletom** [comment]
Howdy @golyalpha, I did not realise this piece of code made its way to Brave but… wow, cool 😃 

I double checked https://publicsuffix.org/list/ and `keybase.pub` does not appear to be listed.
Have you asked to be added to it? Do you think it is relevant to do so?

Otherwise and in the meantime, it is possible [to add custom TLDs](https://github.com/oncletom/tld.js#retrieving-subdomain-of-localhost-and-custom-hostnames) with `#fromUserSettings()`.

Let me know 🙂

**Comment by oncletom** [comment]
@golyalpha I realised I never release what was on `master` so now the published version should be in sync.

**Comment by golyalpha** [comment]
About the relevancy of adding keybase.pub to the Public Suffix List, yes, I do think it is, but someone would need to convince [chris](https://keybase.io/chris) to do so himself, because, for reasons eluding my understanding, you need to own a domain to add it as a public suffix to that list.

About the custom TLD addition, I believe that's precisely what the Brave Browser team has done.

Thanks. :)

**Comment by golyalpha** [comment]
Also, submitted an issue to the brave browser with other public tlds.
These ones are from the Endora webhosting:

tode.cz
8u.cz
9e.cz
mzf.cz
clanweb.eu
mablog.eu
maweb.eu
g6.cz
hys.cz
4fan.cz
cekuj.net
jecool.net
funsite.cz
6f.sk

**Comment by oncletom** [comment]
@golyalpha yeah, Endora could totally add their domains in the publicsuffix list. It is really one of the goals of the list 🙂 

@malgorithms sorry to ping you in this conversation:

> A "public suffix" is one under which Internet users can (or historically could) directly register names. (…) The Public Suffix List is a list of all known public suffixes.

Would you consider add `keybase.pub` as an entry of the Public Suffix list? I guess it would fall into https://github.com/publicsuffix/list/wiki/Guidelines#private-domains

Which means from what I understand:

1. Editing https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat
2. Replace
```
// pub : 2013-12-12 United TLD Holdco Ltd.
pub
```
with
```
// pub : 2013-12-12 United TLD Holdco Ltd.
pub
// Keybase: https://keybase.pub/
// Submitted by Chris Coyne <security@example.com>
keybase.pub
```
3. Adding `_psl.keybase.pub. TXT "ttps://github.com/publicsuffix/list/pull/<id of the PR from above step>"` DNS record

Let me know if it makes sense or if you would like some more background.

PS: I am not related to Public Suffix List nor Brave Payments but happily wire people together 🙂

**Comment by golyalpha** [comment]
Well, I'm gonna say this issue is closed, feel free to reopen it if you don't feel the same, @oncletom.
