### ISSUE TITLE
Invalid behavior for domains ending with a dot '.' (fully qualified domain names)

### ISSUE THREAD

**Issue by remusao** [oncletom/tld.js#95]
Hello there,

I stumbled upon an issue when calling `getPublicSuffix` on domains having a trailing `.` such as `www.google.com.`. My understanding is that the trailing dot should be ignored (it is ignored by browsers): http://www.dns-sd.org/trailingdotsindomainnames.html or https://en.wikipedia.org/wiki/Fully_qualified_domain_name.

```js
> tldjs.getPublicSuffix('www.google.com')
'com'
> tldjs.getPublicSuffix('www.google.com.')
null
```

Similarly for `getDomain`:
```js
> tldjs.getDomain('www.google.com')
'google.com'
> tldjs.getDomain('www.google.com.')
'com.'
```

Should `getPublicSuffix` return `com` in both cases? Or `com.`? Or is `null` acceptable in this case?

Thanks a lot,

**Comment by oncletom** [comment]
Hey, thanks for raising this question 🙂 

It would make sense to accept the `dot` as a suffix character in the case of DNS strings, and actually in any kind of context — and it should be ignored as it is not part of the TLD itself.

```js
> tldjs.getDomain('https://www.google.co.uk./maps')
'google.co.uk'
```

Is that something you could implement? I can't predict for sure if I would have the time to make it happen this week but I'm happy to provide some pointers if you fancy contributing 🙂

**Comment by remusao** [comment]
Hi!

Makes sense. So I guess it should be enough to strip dots at the end of the hostname before trying to extract domain, tld, etc. right? Not sure how the code is organized so I would definitely appreciate some pointers from you if you have some time.

Thanks a lot,

**Comment by oncletom** [comment]
I suspect it would be enough indeed :-)

I guess https://github.com/oncletom/tld.js/blob/master/lib/clean-host.js is a great place to start (and probably to finish). 

And a new test should be added in [test/tld.js](https://github.com/oncletom/tld.js/blob/f611b4e72ebfe7c8a9a34f2aa861d8f3c532758a/test/tld.js#L61):

```js
    it('should ignore the trailing dot in a domain', function () {
      expect(tld.getDomain('www.google.com.')).to.equal('google.com');
    });
```
